apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    com.project.author: kashi
    com.project.name: roboshop
spec:
  containers:
    - name: nginx-lables
      image: nginx
      ports:
      - containerPort: 80
