apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: nginx-resources
      image: nginx
      imagePullPolicy: Always
      resources:
        requests:  # soft limit
          memory: "128Mi"
          cpu: "100m"
        limits: # hard limit
          cpu: "200m"
          memory: "256Mi"