apiVersion: v1
kind: Pod
metadata:
  name: env-variables
spec:
  containers:
    - name: nginx-vars
      image: nginx
      env:
      - name: DEMO_GREETING
        value: "Hello from the environment"
      - name: DEMO_FAREWELL
        value: "Such a sweet sorrow"